language: node_js
before_install:
- npm i -g grunt-cli
- export PATH=$HOME/.local/bin:${PATH}
install:
- npm i
script:
- if [[ $TRAVIS_BRANCH == "master" ]]; then npm run build && grunt deploy --bucket=commits.dasmicrobot.com;
  else npm run build; fi;
env:
  global:
  - secure: RTUtgHgI2fUfILgtEbmNjjjljaf0l4xShzQyep9eZY/vmjDFsH6qgnTdaRIFexT4Y33xEKxtCqKaEXuy8sYjkm1DLpeHs3JvFmX2e9RJ61jdTNPjjuBXs1gBKqIztAzeI0DXK0KuQteRvVJWgPurMPKxdCNdwDE8BUod6zoxZN5hZ1u8R3JXtxjsX7Qq9X9n1uH8tCGk3Xjd089vmEY9zuC46hSQpcMqVvJMVW72J04Oh5UvokZgLQiHjES035bBEhlVe5o0NlRbb5PpfxADspOdIDUusetyM0aBGCD05Tn0m+lVOLVBCV16Uxzgyj1AzDMKrKouPmalFoOgOzl0iZC1nPhIkePK+R6giklx4Dei78vKH5D4SnIe0Sz9TF1rjYo8t/l9Mnsv4zb8ZtPwluxr4oV9bSglZUli81amywp/vX7nj+x4TUouZNx8kkTfNrbz2zpKiUyrEZkYI8dgswr5LzJcJGMyZW6v1+u7fYo9YusUq6lN8s7VOorB+scXPEUP8OCQLofW7OPr+4TdKEA7lUFM+MwC+rSH0XEN79cEKccm5MmF/rGGUgCYGt2krR8A9OtNs9bWSSh1eC401H6N3ENRxGN1wJonPUVMKtzJrNgTXq09+EG2pDkF4d4LsSlxpStbCRPaboY3dg5Kq2z/4DNZdVrzFExd9NQFrG4=
  - secure: gGkkwDgRV+V1WFTfjLBWYdZXrWNf38GJtmkocP0fvgv+f9w3XuK6n/HTMps7u0nDEVRXdKUWccC87JGusmRaNWmowwU326Y0jGYiDnhPLM9ThqTPFDRffuq0M1Ub8osmTtOazn6NorwmsJFRm5VKMBTlMGSm0muB5Mn77JWTJjYcAuCODAbbOzUqI/i+Ny1dz8dshhaLjQFtNT+/pIjYszzkeeXiFj4skcLR80LULRXD29WRBEVlFBhVG1/Q9Xe6efTd4PrAGrbWdbfcpWtAg8ygSbt1L7LE8T1C0yGqKvLbfjYMFIJwC8NgdHtPK5lbH6cI13gF+1Ely8nW4kj6F1Nwjm3ssjXynJAO5cJlfVSQ+n4gAuSvVAJI6t6EX3y+u670o7xhnXLmWbyE28TrZFmBX1njsLqZnZc2Zsz73bH3dyLl1fOZVnGNHzAJVY44p2gRUwY/X0h5KCwCLiz4dV2Uf6RGlce9jxutcW+4B53wUhC3KtwawAbb8cJqzpDkeOEf9g4N50TMxKw/9jwaft7EGrLdxerOJLUJhEpOOVBhc9KS1wCtNcC6hHvjW6MLH/9o/X3+vBU73mJ7ZRWxgtzIjjS2Fpp67M0mAQFnRuIO43xfvFWrOdZYZnqHr1ypj/w6ZMl2BSntbwpTN0vxN3RNeWXEb9jjbs7ni10v8oU=
